title: Alex's Ideas
description: Alex's personal blog and idea imporium
author: Alex Shukhman
github: https://github.com/alexshukhman
about: I'm a developer with his head in the cloud...
google_analytics: UA-107040958-6

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/alex_shukhman"
    - icon: fa-linkedin
      link: "https://linkedin.com/in/alexshukhman"
    - icon: fa-github
      link: "https://github.com/alexshukhman"

urls:
    - text: About Me
      url: https://alexshukhman.com
    - text: Project Links
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://ideas.alexshukhman.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
    
theme: jekyll-theme-minimal